title: TrendOptimizer
description: Set d’indicateurs multi-unités et multi-actifs
url: https://trendoptimizer.fr
theme: null
remote_theme: "mmistakes/minimal-mistakes"   # utilisation en remote theme
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap

# Minimal Mistakes - réglages rapides
logo: /assets/images/TrendOptimizer.fr.png
locale: fr
minimal_mistakes_skin: default  # (contrast, dark, neon, air, etc.)
author:
  name: TrendOptimizer
  avatar: /assets/images/TrendOptimizer.fr black.png
  bio: "Indicateurs pour suivre la tendance, rebonds et renversements."
include: ["_pages"]
